<?php

/**
 * Generated by standard Route::resource
 * @see \Illuminate\Support\Facades\Route::resource()
 */
return [
    new Illuminate\Routing\Route(
        [
            'get',
            'head',
        ],
        'users',
        [
            'as' => 'users.index',
            'uses' => 'App\Http\Controllers\UserController@index',
            'middleware' => [
                'auth:api',
            ],
            'controller' => 'App\Http\Controllers\UserController@index',
        ],
    ),
    new Illuminate\Routing\Route(
        [
            'get',
            'head',
        ],
        'users/create',
        [
            'as' => 'users.create',
            'uses' => 'App\Http\Controllers\UserController@create',
            'middleware' => [
                'auth:api',
            ],
            'controller' => 'App\Http\Controllers\UserController@create',
        ],
    ),
    new Illuminate\Routing\Route(
        [
            'post',
        ],
        'users',
        [
            'as' => 'users.store',
            'uses' => 'App\Http\Controllers\UserController@store',
            'middleware' => [
                'auth:api',
            ],
            'controller' => 'App\Http\Controllers\UserController@store',
        ],
    ),
    new Illuminate\Routing\Route(
        [
            'get',
            'head',
        ],
        'users/{user}',
        [
            'as' => 'users.show',
            'uses' => 'App\Http\Controllers\UserController@show',
            'middleware' => [
                'auth:api',
            ],
            'controller' => 'App\Http\Controllers\UserController@show',
        ],
    ),
    new Illuminate\Routing\Route(
        [
            'get',
            'head',
        ],
        'users/{user}/edit',
        [
            'as' => 'users.edit',
            'uses' => 'App\Http\Controllers\UserController@edit',
            'middleware' => [
                'auth:api',
            ],
            'controller' => 'App\Http\Controllers\UserController@edit',
        ],
    ),
    new Illuminate\Routing\Route(
        [
            'put',
            'patch',
        ],
        'users/{user}',
        [
            'as' => 'users.update',
            'uses' => 'App\Http\Controllers\UserController@update',
            'middleware' => [
                'auth:api',
            ],
            'controller' => 'App\Http\Controllers\UserController@update',
        ],
    ),
    new Illuminate\Routing\Route(
        [
            'DELETE',
        ],
        'users/{user}',
        [
            'as' => 'users.destroy',
            'uses' => 'App\Http\Controllers\UserController@destroy',
            'middleware' => [
                'auth:api',
            ],
            'controller' => 'App\Http\Controllers\UserController@destroy',
        ],
    ),
];
